name: caller-java-workflow

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  call-java-workflow:
      uses: Witton-s/pipeline-template/.github/workflows/reusable-java-workflow.yml@main
  download-artifacts:
      runs-on: ubuntu-latest
      needs: call-java-workflow
      steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-files

      - run: ls -R
      - run: cat test.txt

      - name: Set up JDK 17
      - uses: actions/setup-java@v3
        with:
           java-version: '17'

      - run: java -jar build/libs/helloworld-1.0.0.jar 

      


